{
  allFormSubmissions {
    edges {
      node {
        id
        signature
        submittedAt
        data
        form {
          name
          description
          jsCode
        }
      }
    }
  }
}